site_name: EasyBuild blog
theme:
  name: material
  logo: img/logos/EasyBuild.png
  favicon: img/logos/EasyBuild.png
nav: 
plugins:
  - blog:
      archive: false
      blog_dir: .
      blog_toc: true
